# Generated by Django 4.0.4 on 2022-08-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('start_datetime', models.DateTimeField(verbose_name='Start DateTime')),
                ('start_month', models.CharField(max_length=50, verbose_name='Start Month')),
                ('start_year', models.CharField(max_length=50, verbose_name='Start Year')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateField(auto_now=True, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='FieldMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocType', models.CharField(max_length=50)),
                ('Field_Name', models.CharField(max_length=50)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportsMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Document_Type', models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Sales Return', 'Sales Return'), ('Opening Balance', 'Opening Balance'), ('Purchase Document', 'Purchase Document'), ('Purchase Return Document', 'Purchase Return Document'), ('Delivery Note', 'Delivery Note'), ('Receipt Note', 'Receipt Note')], max_length=50, null=True, verbose_name='Document Type')),
                ('value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Value')),
                ('Date_Type', models.CharField(blank=True, choices=[('Creation Date', 'Creation Date'), ('Date', 'Date')], max_length=50, null=True, verbose_name='Date Type')),
                ('From_Date', models.DateField(verbose_name='From Date')),
                ('To_Date', models.DateField(verbose_name='To Date')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportsapp.fieldmaster', verbose_name='Field Type')),
            ],
        ),
    ]
