# Generated by Django 4.0.4 on 2022-11-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=50, unique=True, verbose_name='Menu Name')),
                ('Pmenu', models.IntegerField(default=0, verbose_name='Root Menu')),
                ('pagelink', models.CharField(blank=True, max_length=50, null=True, verbose_name='Page Link')),
                ('Dord', models.IntegerField(blank=True, null=True, verbose_name='Decending Order')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='MenuMaster/Images')),
                ('Roles', models.CharField(blank=True, max_length=100, null=True, verbose_name='Role')),
                ('IsMobile', models.IntegerField(default=0)),
                ('MTYPE', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
