# Generated by Django 4.0.4 on 2022-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0003_remove_menumaster_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='pagelink',
            field=models.URLField(blank=True, max_length=50, null=True, verbose_name='Page Link'),
        ),
    ]
