# Generated by Django 4.0.4 on 2022-11-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0004_menumaster_pagelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumaster',
            name='IsMobile',
        ),
    ]
