# Generated by Django 4.0.4 on 2022-11-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0005_remove_menumaster_ismobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='IsMobile',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
