# Generated by Django 4.0.4 on 2022-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0008_alter_menumaster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menucode', models.IntegerField()),
                ('menuname', models.CharField(max_length=100)),
                ('menutype', models.IntegerField()),
            ],
        ),
    ]
