# Generated by Django 4.0.4 on 2022-12-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0010_menumaster_faicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumaster',
            name='pagelink',
        ),
    ]
