# Generated by Django 4.0.4 on 2022-12-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0012_menumaster_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='Is_Create',
            field=models.BooleanField(default=False, verbose_name='Is Create'),
        ),
        migrations.AddField(
            model_name='menumaster',
            name='Is_View',
            field=models.BooleanField(default=False, verbose_name='Is View'),
        ),
        migrations.AddField(
            model_name='menumaster',
            name='is_Delete',
            field=models.BooleanField(default=False, verbose_name='Is Delete'),
        ),
        migrations.AddField(
            model_name='menumaster',
            name='is_Edit',
            field=models.BooleanField(default=False, verbose_name='Is Edit'),
        ),
    ]
