# Generated by Django 4.0.4 on 2022-12-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0013_menumaster_is_create_menumaster_is_view_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EID', models.PositiveIntegerField(blank=True, null=True)),
                ('UID', models.PositiveBigIntegerField()),
                ('ROLEID', models.PositiveIntegerField(blank=True, null=True)),
                ('fld1', models.CharField(blank=True, max_length=500, null=True)),
                ('fld2', models.CharField(blank=True, max_length=300, null=True)),
                ('fld3', models.CharField(blank=True, max_length=300, null=True)),
                ('fld4', models.CharField(blank=True, max_length=300, null=True)),
                ('fld5', models.CharField(blank=True, max_length=300, null=True)),
                ('fld6', models.CharField(blank=True, max_length=300, null=True)),
                ('fld7', models.CharField(blank=True, max_length=300, null=True)),
                ('fld8', models.CharField(blank=True, max_length=300, null=True)),
                ('fld9', models.CharField(blank=True, max_length=300, null=True)),
                ('fld10', models.CharField(blank=True, max_length=300, null=True)),
                ('fld11', models.CharField(blank=True, max_length=300, null=True)),
                ('rolename', models.CharField(max_length=50)),
                ('documenttype', models.CharField(max_length=50)),
                ('iscreate', models.BooleanField(default=False)),
                ('isedit', models.BooleanField(default=False)),
                ('isview', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
