# Generated by Django 4.0.4 on 2023-01-09 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_user_image'),
        ('reportsapp', '0014_roleassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='distributors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.distributor'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reportsapp.reportsmaster'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='zones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.zone'),
        ),
        migrations.AlterField(
            model_name='reportsmaster',
            name='Document_Type',
            field=models.CharField(blank=True, choices=[('Sales', 'Sales'), ('Sales Return', 'Sales Return'), ('Opening Balance', 'Opening Balance'), ('Purchase Document', 'Purchase Document'), ('Purchase Return Document', 'Purchase Return Document'), ('Delivery Note', 'Delivery Note'), ('Item', 'Item'), ('Hierarchy1', 'Hierarchy1'), ('Hierarchy2', 'Hierarchy2'), ('Hierarchy3', 'Hierarchy3'), ('Hierarchy4', 'Hierarchy4'), ('Hierarchy5', 'Hierarchy5'), ('Distributor', 'Distributor'), ('Customer', 'Customer'), ('Zone', 'Zone')], max_length=50, null=True, verbose_name='Document Type'),
        ),
    ]
