# Generated by Django 4.0.4 on 2023-01-13 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0015_roleassignment_distributors_roleassignment_documents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleassignment',
            name='distributors',
        ),
        migrations.RemoveField(
            model_name='roleassignment',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='roleassignment',
            name='zones',
        ),
    ]
