# Generated by Django 4.0.4 on 2023-01-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_user_image'),
        ('reportsapp', '0016_remove_roleassignment_distributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleassignment',
            name='distributors',
            field=models.ManyToManyField(blank=True, null=True, to='account.distributor', verbose_name='Distributor'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='reportsapp.reportsmaster', verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='zones',
            field=models.ManyToManyField(blank=True, null=True, to='account.zone', verbose_name='Zone'),
        ),
    ]
