# Generated by Django 4.0.4 on 2023-01-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0044_user_image'),
        ('reportsapp', '0017_roleassignment_distributors_roleassignment_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumaster',
            name='usrole',
            field=models.ManyToManyField(blank=True, null=True, to='account.rolemaster', verbose_name='ROLE'),
        ),
    ]
