# Generated by Django 4.0.4 on 2023-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0022_alter_reportsmaster_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsmaster',
            name='Document_Type',
            field=models.CharField(blank=True, choices=[('Sales', 'Sales Order'), ('salesInvoice', 'sales Invoice'), ('Sales Return', 'Sales Return'), ('Opening Balance', 'Opening Balance'), ('Purchase Document', 'Purchase Order'), ('PurchaseInvoice', 'Purchase Invoice'), ('Purchase Return Document', 'Purchase Return Document'), ('Delivery Note', 'Delivery Note'), ('Receipt_Note', 'Material Receipt Note')], max_length=50, null=True, verbose_name='Document Type'),
        ),
    ]
