# Generated by Django 4.0.4 on 2023-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0024_alter_reportsmaster_date_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockstatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='Document Type')),
                ('docid', models.IntegerField(default=0, verbose_name='Document ID')),
                ('doc_date', models.DateField(verbose_name='Document Date')),
                ('warehouse_id', models.IntegerField(default=0, verbose_name='Warehouse ID')),
                ('warehouse_name', models.CharField(max_length=50, verbose_name='Warehouse Name')),
                ('items', models.IntegerField(default=0, verbose_name='Item ID')),
                ('item_name', models.CharField(max_length=50, verbose_name='Item Name')),
                ('Qyn', models.IntegerField(default=0, verbose_name='Quantity')),
                ('uom', models.CharField(max_length=50, verbose_name='UOM')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
        ),
    ]
