# Generated by Django 4.0.4 on 2023-06-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0025_stockstatement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockstatement',
            old_name='Qyn',
            new_name='Qty',
        ),
    ]
