# Generated by Django 4.0.4 on 2023-07-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0207_alter_detailofpurchase_purchases_quantity'),
        ('reportsapp', '0028_qtystatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qtystatement',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.item', verbose_name='Item ID'),
        ),
        migrations.AlterField(
            model_name='qtystatement',
            name='warehouse_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.warehouse', verbose_name='Warehouse ID'),
        ),
    ]
