# Generated by Django 4.0.4 on 2023-07-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0029_alter_qtystatement_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qtystatement',
            name='document_order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
