# Generated by Django 4.0.4 on 2023-08-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0219_stocksummary_uom'),
        ('reportsapp', '0030_qtystatement_document_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockstatement',
            name='itm',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='account.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockstatement',
            name='w_house',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='account.warehouse'),
            preserve_default=False,
        ),
    ]
