# Generated by Django 4.0.4 on 2023-08-02 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportsapp', '0031_stockstatement_itm_stockstatement_w_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stockstatement',
        ),
    ]
