# Generated by Django 4.0.4 on 2022-10-11 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='Region',
        ),
    ]
