# Generated by Django 4.0.4 on 2022-10-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_distributor_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='Region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
