# Generated by Django 4.0.4 on 2022-10-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_distributor_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.regionmaster'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='zones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.zone'),
        ),
    ]
