# Generated by Django 4.0.4 on 2022-10-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_distributor_region_distributor_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_detail',
            name='entity_id',
            field=models.PositiveIntegerField(default=0, verbose_name='TID'),
        ),
    ]
