# Generated by Django 4.0.4 on 2022-10-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_sales_detail_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opening_balance_child',
            name='entity_id',
            field=models.IntegerField(null=True, verbose_name='TID'),
        ),
        migrations.AlterField(
            model_name='sales_return_detail',
            name='entity_id',
            field=models.IntegerField(null=True, verbose_name='TID'),
        ),
    ]
