# Generated by Django 4.0.4 on 2022-10-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_delivery_note_details_entity_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbpricemaster',
            name='Rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='Total_Inventory_Amount',
            field=models.CharField(default=0, max_length=100, verbose_name='Total Inventory Amount'),
        ),
        migrations.AlterField(
            model_name='item',
            name='GST_Rate',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='MRP',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='opening_balance_child',
            name='Discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Sales Discount(%)'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='Total_GST',
            field=models.FloatField(default=0, null=True, verbose_name='Total GST(%)'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='Total_Inventory_Amount',
            field=models.FloatField(default=0, null=True, verbose_name='Total Inventory Amount'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='Total_Inventory_Amount',
            field=models.FloatField(default=0, null=True, verbose_name='Total Inventory Amount'),
        ),
        migrations.AlterField(
            model_name='receipt_note',
            name='Total_Inventory_Amount',
            field=models.CharField(default=0, max_length=100, verbose_name='Total Inventory Amount'),
        ),
        migrations.AlterField(
            model_name='sales_detail',
            name='Sales_Discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Sales Discount(%)'),
        ),
        migrations.AlterField(
            model_name='sales_detail',
            name='Sales_Rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='sales_return_detail',
            name='Sales_Discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Sales Discount(%)'),
        ),
    ]
