# Generated by Django 4.0.4 on 2022-10-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_dbpricemaster_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_child',
            name='sr',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial_No'),
        ),
    ]
