# Generated by Django 4.0.4 on 2022-10-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_item_hierarchy4_remove_item_hierarchy5'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Hierarchy4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hierarchy4'),
        ),
        migrations.AddField(
            model_name='item',
            name='Hierarchy5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hierarchy5'),
        ),
    ]
