# Generated by Django 4.0.4 on 2022-10-13 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_item_hierarchy4_item_hierarchy5'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Hierarchy4',
            new_name='Hier4',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Hierarchy5',
            new_name='Hier5',
        ),
    ]
