# Generated by Django 4.0.4 on 2022-10-13 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_rename_hierarchy4_item_hier4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Hier4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hierarchy4', verbose_name='Hierarchy4'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Hier5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hierarchy5', verbose_name='Hierarchy5'),
        ),
        migrations.AlterField(
            model_name='item',
            name='Principal_Company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
