# Generated by Django 4.0.4 on 2022-10-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_item_hier4_alter_item_hier5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tax_Type', models.CharField(choices=[('GST(%)', 'GST(%)'), ('VAT(%)', 'VAT(%)')], max_length=20, verbose_name='Tax Type')),
                ('name', models.CharField(max_length=30, verbose_name='Tax Name')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Tax Value(%)')),
            ],
        ),
    ]
