# Generated by Django 4.0.4 on 2022-10-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_taxmaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxmaster',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Tax Name'),
        ),
    ]
