# Generated by Django 4.0.4 on 2022-10-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_taxmaster_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxmaster',
            name='Tax_Type',
            field=models.CharField(choices=[('GST', 'GST'), ('VAT', 'VAT')], max_length=20, verbose_name='Tax Type'),
        ),
    ]
