# Generated by Django 4.0.4 on 2022-10-16 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_taxmaster_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxmaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 16, 11, 45, 31, 643693)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
