# Generated by Django 4.0.4 on 2022-10-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_taxmaster_created_on_taxmaster_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='GST_Rate',
        ),
    ]
