# Generated by Django 4.0.4 on 2022-10-17 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_item_gst_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='GST_Rate',
        ),
    ]
