# Generated by Django 4.0.4 on 2022-10-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_item_taxrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opening_balance_child',
            name='Item_Code',
        ),
        migrations.RemoveField(
            model_name='opening_balance_child',
            name='Opening_stock_Details',
        ),
        migrations.RemoveField(
            model_name='closingbalance',
            name='openingbalance',
        ),
        migrations.RemoveField(
            model_name='closingbalance',
            name='openingbalancechild',
        ),
        migrations.RemoveField(
            model_name='stock_child',
            name='Stock',
        ),
        migrations.RemoveField(
            model_name='stockmaster',
            name='openingbalance',
        ),
        migrations.RemoveField(
            model_name='stockmaster',
            name='openingbalancechild',
        ),
        migrations.DeleteModel(
            name='Opening_Balance',
        ),
        migrations.DeleteModel(
            name='Opening_Balance_Child',
        ),
    ]
