# Generated by Django 4.0.4 on 2022-10-19 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_remove_opening_balance_child_item_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Distributor',
        ),
    ]
