# Generated by Django 4.0.4 on 2022-10-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_customer_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Distributor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Distributor_Name'),
        ),
    ]
