# Generated by Django 4.0.4 on 2022-10-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_customer_distributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note_details',
            name='Quantity',
            field=models.PositiveIntegerField(verbose_name='Sales Quantity'),
        ),
        migrations.AlterField(
            model_name='delivery_note_details',
            name='Serial_No',
            field=models.CharField(max_length=50, verbose_name='Sales Serial No'),
        ),
        migrations.AlterField(
            model_name='delivery_note_details',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item', verbose_name='Sales Item Code'),
        ),
    ]
