# Generated by Django 4.0.4 on 2022-10-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_alter_delivery_note_details_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note_details',
            name='Amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Amount'),
        ),
    ]
