# Generated by Django 4.0.4 on 2022-10-31 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_uom_base_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='UOM',
        ),
    ]
