# Generated by Django 4.0.4 on 2022-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_remove_item_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_uom',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_uom',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_uom',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
