# Generated by Django 4.0.4 on 2022-11-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_item_base_uom_item_purchase_uom_item_sale_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_return_detail',
            name='sale_uom',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
