# Generated by Django 4.0.4 on 2022-11-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_sales_detail_sale_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailofpurchase',
            name='purchase_uom',
            field=models.CharField(max_length=50, null=True, verbose_name='Purchase UOM'),
        ),
        migrations.AddField(
            model_name='detailsofpurchasereturn',
            name='purchase_uom',
            field=models.CharField(max_length=50, null=True, verbose_name='Purchase UOM'),
        ),
    ]
