# Generated by Django 4.0.4 on 2022-11-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0036_detailofpurchase_purchase_uom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_child',
            name='base_uom',
            field=models.CharField(max_length=50, null=True, verbose_name='Base UOM'),
        ),
    ]
