# Generated by Django 4.0.4 on 2022-11-03 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_stock_child_base_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmaster',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='zons', to='account.zone'),
        ),
        migrations.AlterField(
            model_name='sales_return_detail',
            name='sale_uom',
            field=models.CharField(max_length=50, null=True, verbose_name='Sales UOM'),
        ),
    ]
