# Generated by Django 4.0.4 on 2022-11-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_alter_regionmaster_zone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Region',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='State',
            new_name='state',
        ),
    ]
