# Generated by Django 4.0.4 on 2022-11-04 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_rename_city_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regionmaster',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.zone'),
        ),
    ]
