# Generated by Django 4.0.4 on 2022-11-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0040_alter_regionmaster_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='zones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.zone', verbose_name='Zone'),
        ),
    ]
