# Generated by Django 4.0.4 on 2022-11-15 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0041_alter_distributor_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 15, 12, 13, 21, 448674)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citymaster',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='regionmaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 15, 12, 13, 29, 847315)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regionmaster',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statemaster',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 15, 12, 13, 37, 182764)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statemaster',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
