# Generated by Django 4.0.4 on 2022-11-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0042_citymaster_created_on_citymaster_updated_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Profile Pic'),
        ),
    ]
