# Generated by Django 4.0.4 on 2023-02-15 11:47

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0046_stock_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
