# Generated by Django 4.0.4 on 2023-02-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0047_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Arole',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
