# Generated by Django 4.0.4 on 2023-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_user_arole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, editable=False)),
                ('wcode', models.CharField(max_length=50, verbose_name='Warehouse Code')),
                ('wname', models.CharField(max_length=50, verbose_name='Warehouse Name')),
            ],
        ),
    ]
