# Generated by Django 4.0.4 on 2023-03-03 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0051_warehouse_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='warehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseName', models.CharField(blank=True, max_length=50, null=True)),
                ('itemName', models.CharField(blank=True, max_length=80, null=True, verbose_name='ItemName')),
                ('Date', models.DateField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item')),
                ('warehouseCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.warehouse', verbose_name='Warehouse Code')),
            ],
            options={
                'verbose_name': 'warehouse wise item stock',
            },
        ),
        migrations.CreateModel(
            name='warehouseItemChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouseID', models.IntegerField()),
                ('Item_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Quantity', models.PositiveIntegerField()),
                ('base_uom', models.CharField(max_length=50, null=True, verbose_name='Base UOM')),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=20)),
                ('SNo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial No')),
                ('Batch', models.CharField(blank=True, max_length=50, null=True)),
                ('Discount', models.PositiveIntegerField(null=True, verbose_name='Sales Discount(%)')),
                ('Total_Amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Reference_No', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('Item_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item')),
            ],
        ),
    ]
