# Generated by Django 4.0.4 on 2023-03-10 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0052_warehousestock_warehouseitemchild'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestock',
            name='items',
        ),
    ]
