# Generated by Django 4.0.4 on 2023-03-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0053_remove_warehousestock_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitemchild',
            name='warehouseID',
            field=models.IntegerField(null=True, verbose_name='Warehouse Id'),
        ),
    ]
