# Generated by Django 4.0.4 on 2023-03-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0054_alter_warehouseitemchild_warehouseid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocument',
            name='Bill_Date',
            field=models.DateField(verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='SAP_Order_Date',
            field=models.DateField(verbose_name='Supplier Invoice Date'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='SAP_Order_No',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order No'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='Vendor_Name',
            field=models.CharField(choices=[('Johnson and Johnson Surgical Vision India Pvt. Ltd.', 'Johnson and Johnson Surgical Vision India Pvt. Ltd.'), ('Johnson and Johnson .', 'Johnson and Johnson ')], max_length=100, verbose_name='Billing Entity'),
        ),
    ]
