# Generated by Django 4.0.4 on 2023-03-13 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0055_alter_purchasedocument_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='gst_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taxmaster', verbose_name='GST Type'),
        ),
    ]
