# Generated by Django 4.0.4 on 2023-03-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0056_purchasedocument_gst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocument',
            name='Total_GST',
            field=models.FloatField(default=0, null=True, verbose_name='Total GST Amount'),
        ),
    ]
