# Generated by Django 4.0.4 on 2023-03-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0059_taxmaster_cgst_taxmaster_sgst'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxmaster',
            name='taxinputrecoverable',
            field=models.BooleanField(default=False, verbose_name='Tax Input Recoverable'),
        ),
    ]
