# Generated by Django 4.0.4 on 2023-03-16 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0062_alter_warehousestock_warehousename'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturndocument',
            name='distributor_name',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Distributor Name'),
        ),
        migrations.AddField(
            model_name='purchasereturndocument',
            name='gst_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taxmaster', verbose_name='GST Type'),
        ),
        migrations.AddField(
            model_name='purchasereturndocument',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=19, verbose_name='Total Discount Amount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='Bill_Date',
            field=models.DateField(verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='SAP_Order_Date',
            field=models.DateField(verbose_name='Supplier Invoice Date'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='SAP_Order_No',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order No'),
        ),
    ]
