# Generated by Django 4.0.4 on 2023-03-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0063_purchasereturndocument_distributor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='distributor_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Distributor Name'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='total_discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total Discount Amount'),
        ),
    ]
