# Generated by Django 4.0.4 on 2023-03-17 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0065_alter_purchasereturndocument_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distributor_Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Distributor Name')),
                ('Bill_Date', models.DateField(verbose_name='Purchase Invoice Date')),
                ('Supplier_Invoice_No', models.CharField(max_length=50, verbose_name='Supplier Invoice No')),
                ('SAP_Order_No', models.CharField(blank=True, max_length=50, null=True, verbose_name='Purchase Invoice No')),
                ('SAP_Order_Date', models.DateField(verbose_name='Supplier Invoice Date')),
                ('Total_Inventory_Amount', models.FloatField(default=0, null=True, verbose_name='Total Inventory Amount')),
                ('Total_GST', models.FloatField(default=0, null=True, verbose_name='Total GST Amount')),
                ('SGST_AMOUNT', models.FloatField(blank=True, default=0, null=True, verbose_name='SGST AMOUNT')),
                ('CGST_AMOUNT', models.FloatField(blank=True, default=0, null=True, verbose_name='CGST AMOUNT')),
                ('IGST_AMOUNT', models.FloatField(blank=True, default=0, null=True, verbose_name='IGST AMOUNT')),
                ('Vendor_Name', models.CharField(choices=[('Johnson and Johnson Surgical Vision India Pvt. Ltd.', 'Johnson and Johnson Surgical Vision India Pvt. Ltd.'), ('Johnson and Johnson .', 'Johnson and Johnson ')], max_length=100, verbose_name='Billing Entity')),
                ('PO_No', models.CharField(blank=True, max_length=50, null=True, verbose_name='PO No')),
                ('Total_Invoice_Amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total Invoice Amount')),
                ('total_discount_amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Total Discount Amount')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Distributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.distributor', verbose_name='Distributor Code')),
                ('gst_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taxmaster', verbose_name='GST Type')),
            ],
            options={
                'verbose_name': 'Purchase Invoice',
            },
        ),
    ]
