# Generated by Django 4.0.4 on 2023-03-17 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0066_purchaseinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseinvoicelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=30, null=True, verbose_name='TID')),
                ('item_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name')),
                ('Quantity', models.PositiveIntegerField(verbose_name='Quantity')),
                ('UOM', models.CharField(max_length=50, null=True, verbose_name='UOM')),
                ('Rate', models.FloatField(verbose_name='Purchase Rate')),
                ('Discount', models.FloatField(blank=True, default=0, null=True, verbose_name='Discount(%)')),
                ('Serial_No', models.CharField(max_length=50, verbose_name='Serial No')),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Amount')),
                ('Total_Amounts', models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Amounts')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item', verbose_name='Item Code')),
            ],
        ),
    ]
