# Generated by Django 4.0.4 on 2023-03-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0068_alter_purchaseinvoicelineitem_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distributor_Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Distributor Name')),
                ('Customer_Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Name')),
                ('Bill_Date', models.DateField(verbose_name='Sales Invoice Date')),
                ('Invoice_No', models.CharField(max_length=50, verbose_name='Invoice No')),
                ('Total_Inventory_Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Inventory Amount')),
                ('Total_GST', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total GST Amount')),
                ('SGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=20, null=True, verbose_name='SGST Amount')),
                ('CGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=20, null=True, verbose_name='CGST Amount')),
                ('IGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='IGST Amount')),
                ('Cash_Discount_Amount', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=20, null=True, verbose_name='Sales Discount Amount')),
                ('R_O_Amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='RO Amount')),
                ('Total_Invoice_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Total Invoice Amount')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='Customer Code')),
                ('Distributors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.distributor', verbose_name='Distributor Code')),
            ],
        ),
    ]
