# Generated by Django 4.0.4 on 2023-03-17 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0069_salesinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='saleinvoicelineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.PositiveIntegerField(default=0, verbose_name='TID')),
                ('Item_Name', models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='Item Name')),
                ('Quantity', models.PositiveIntegerField()),
                ('uom', models.CharField(max_length=50, null=True, verbose_name='UOM')),
                ('Rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Serial_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Batch', models.CharField(blank=True, max_length=50, null=True)),
                ('Discount', models.PositiveIntegerField(default=0, null=True, verbose_name='Discount(%)')),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('Reference_No', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('Item_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item', verbose_name='Item Code')),
            ],
            options={
                'verbose_name': 'Sales Detail',
            },
        ),
    ]
