# Generated by Django 4.0.4 on 2023-03-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0072_purchaseinvoice_purchase_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='Bill_Date',
            field=models.DateField(verbose_name='Purchase Order Date'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='purchase_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.purchasedocument', verbose_name='Purchase Order No'),
        ),
    ]
