# Generated by Django 4.0.4 on 2023-03-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0074_purchaseinvoice_purchase_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleinvoicelineitem',
            name='Item_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='CGST_AMOUNT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='CGST Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Cash_Discount_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Sales Discount Amount'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='SGST_AMOUNT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='SGST Amount'),
        ),
    ]
