# Generated by Django 4.0.4 on 2023-03-20 09:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0075_alter_saleinvoicelineitem_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='sale_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.sales', verbose_name='Sales Order No'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sale_order_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 20, 9, 41, 20, 707235), verbose_name='Sale Order Date'),
            preserve_default=False,
        ),
    ]
