# Generated by Django 4.0.4 on 2023-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0076_salesinvoice_sale_order_salesinvoice_sale_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='sale_order_date',
            field=models.DateField(verbose_name='Sales Order Date'),
        ),
    ]
