# Generated by Django 4.0.4 on 2023-03-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0077_alter_salesinvoice_sale_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='Invoice_No',
            field=models.CharField(max_length=50, verbose_name='Sales Invoice No'),
        ),
    ]
