# Generated by Django 4.0.4 on 2023-03-20 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0079_alter_sales_bill_date_alter_sales_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='gst_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taxmaster', verbose_name='GST Type'),
        ),
    ]
