# Generated by Django 4.0.4 on 2023-03-20 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0080_salesinvoice_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='gst_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taxmaster', verbose_name='GST Type'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='gst_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taxmaster', verbose_name='GST Type'),
        ),
    ]
