# Generated by Django 4.0.4 on 2023-03-21 11:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0081_sales_gst_type_salesreturn_gst_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='sale_return_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.salesinvoice', verbose_name='Sales Return Order No'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sale_return_order_Date',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 11, 47, 16, 338945), verbose_name='Sales Return Order Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='Bill_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='Invoice_No',
            field=models.CharField(max_length=20, verbose_name='Sales Return Invoice No'),
        ),
    ]
