# Generated by Django 4.0.4 on 2023-03-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_salesreturn_sale_return_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturn',
            name='Tally_Master_ID',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
