# Generated by Django 4.0.4 on 2023-03-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_alter_salesreturn_tally_master_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentType', models.CharField(choices=[('Sales', 'Sales'), ('salesInvoice', 'sales Invoice'), ('SalesReturn', 'Sales Return'), ('PurchaseDocument', 'Purchase Document'), ('PurchaseInvoice', 'Purchase Invoice'), ('PurchaseReturnDocument', 'Purchase Return Document'), ('Delivery_Note', 'Delivery Note'), ('Receipt_Note', 'Receipt Note')], max_length=30, verbose_name='Document Type')),
                ('seprator_choice', models.CharField(blank=True, choices=[('0', '/'), ('1', '-'), ('1', ':'), ('1', '_')], max_length=30, null=True, verbose_name='Separtor')),
                ('prfx', models.CharField(blank=True, max_length=20, null=True, verbose_name='Prefix')),
                ('Field_selection', models.CharField(choices=[('0', 'Auto Number'), ('1', 'New Auto Number')], max_length=30, verbose_name='Field Selection')),
                ('num_sequence', models.IntegerField(blank=True, null=True, verbose_name='Number Sequence')),
                ('auto_no', models.IntegerField(blank=True, null=True, verbose_name='Auto Number')),
                ('New_auto_no', models.IntegerField(blank=True, null=True, verbose_name='New Auto Number')),
                ('Doc_field', models.CharField(blank=True, max_length=50, null=True, verbose_name='Document Field')),
                ('sufx', models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix')),
                ('use_FY_as_prfx', models.BooleanField(default=False, verbose_name='Use FY as Prefix')),
                ('use_FY_as_sufx', models.BooleanField(default=False, verbose_name='Use FY as Suffix')),
                ('FY', models.DateField(blank=True, null=True, verbose_name='FY')),
                ('Fmonth', models.DateField(blank=True, null=True, verbose_name='FY Month')),
                ('use_month_as_prfx', models.BooleanField(default=False, verbose_name='Use Month as Prefix')),
                ('use_month_as_sufx', models.BooleanField(default=False, verbose_name='Use Month as suffix')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
