# Generated by Django 4.0.4 on 2023-03-23 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_ordergenerator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderGenerator',
        ),
    ]
