# Generated by Django 4.0.4 on 2023-03-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0087_ordergenerator_seqnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergenerator',
            name='documentType',
            field=models.CharField(choices=[('Sales', 'Sales Order'), ('salesInvoice', 'sales Invoice'), ('SalesReturn', 'Sales Return'), ('PurchaseDocument', 'Purchase Order'), ('PurchaseInvoice', 'Purchase Invoice'), ('PurchaseReturnDocument', 'Purchase Return'), ('Delivery_Note', 'Delivery Note'), ('Receipt_Note', 'Matrial Receipt Note')], max_length=30, unique=True, verbose_name='Document Type'),
        ),
    ]
