# Generated by Django 4.0.4 on 2023-03-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0088_alter_ordergenerator_documenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergenerator',
            name='FY',
        ),
        migrations.AlterField(
            model_name='ordergenerator',
            name='seprator_choice',
            field=models.CharField(blank=True, choices=[('/', '/'), ('-', '-'), (':', ':'), ('_', '_')], max_length=30, null=True, verbose_name='Separtor'),
        ),
    ]
