# Generated by Django 4.0.4 on 2023-03-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0090_ordergenerator_fy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergenerator',
            name='Fmonth',
        ),
    ]
