# Generated by Django 4.0.4 on 2023-03-23 13:53

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0091_remove_ordergenerator_fmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergenerator',
            name='Fmonth',
            field=models.IntegerField(default=account.models.current_month, verbose_name='month'),
        ),
    ]
