# Generated by Django 4.0.4 on 2023-03-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0092_ordergenerator_fmonth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergenerator',
            name='seqnum',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name=' Start Number Sequence'),
        ),
    ]
