# Generated by Django 4.0.4 on 2023-03-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0093_alter_ordergenerator_seqnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergenerator',
            name='Document_for_prefix',
            field=models.CharField(choices=[('Sales', 'Sales Order'), ('salesInvoice', 'sales Invoice'), ('SalesReturn', 'Sales Return'), ('PurchaseDocument', 'Purchase Order'), ('PurchaseInvoice', 'Purchase Invoice'), ('PurchaseReturnDocument', 'Purchase Return'), ('Delivery_Note', 'Delivery Note'), ('Receipt_Note', 'Matrial Receipt Note')], default=1, max_length=30, verbose_name='Document for prefix'),
            preserve_default=False,
        ),
    ]
