# Generated by Django 4.0.4 on 2023-03-24 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0094_ordergenerator_document_for_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_note',
            name='gst_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taxmaster', verbose_name='GST Type'),
        ),
        migrations.AlterField(
            model_name='receipt_note',
            name='Bill_Date',
            field=models.DateField(verbose_name='Order Date'),
        ),
        migrations.AlterField(
            model_name='receipt_note',
            name='Invoice_No',
            field=models.CharField(max_length=100, verbose_name='Order No'),
        ),
    ]
