# Generated by Django 4.0.4 on 2023-03-24 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0095_receipt_note_gst_type_alter_receipt_note_bill_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_note',
            name='order_no',
            field=models.ForeignKey(default=35, on_delete=django.db.models.deletion.CASCADE, to='account.purchasedocument', verbose_name='Order Number'),
            preserve_default=False,
        ),
    ]
