# Generated by Django 4.0.4 on 2023-03-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0097_alter_receipt_note_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_note',
            name='Total_GST',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Gst Amount'),
        ),
    ]
