# Generated by Django 4.0.4 on 2023-03-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0099_alter_receipt_note_detail_serial_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_note_detail',
            name='Quantity',
            field=models.PositiveIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='receipt_note_detail',
            name='Total_Amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='receipt_note_detail',
            name='items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item', verbose_name='Item Code'),
        ),
    ]
