# Generated by Django 4.0.4 on 2023-03-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0100_alter_receipt_note_detail_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergenerator',
            name='order_combination',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Order Combination'),
        ),
    ]
