# Generated by Django 4.0.4 on 2023-03-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0101_ordergenerator_order_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergenerator',
            name='Document_for_prefix',
            field=models.CharField(blank=True, choices=[('Sales', 'Sales Order'), ('salesInvoice', 'sales Invoice'), ('SalesReturn', 'Sales Return'), ('PurchaseDocument', 'Purchase Order'), ('PurchaseInvoice', 'Purchase Invoice'), ('PurchaseReturnDocument', 'Purchase Return'), ('Delivery_Note', 'Delivery Note'), ('Receipt_Note', 'Matrial Receipt Note')], max_length=30, null=True, verbose_name='Document for prefix'),
        ),
    ]
