# Generated by Django 4.0.4 on 2023-03-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0102_alter_ordergenerator_document_for_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note',
            name='Customer_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Name'),
        ),
    ]
