# Generated by Django 4.0.4 on 2023-03-31 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0103_delivery_note_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note',
            name='sales_order_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 31, 11, 53, 37, 566671), verbose_name='Sales Order Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='sales_order_no',
            field=models.ForeignKey(default=77, on_delete=django.db.models.deletion.CASCADE, to='account.sales', verbose_name='Sales Order No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='Invoice_No',
            field=models.CharField(max_length=100, verbose_name='SalesInvoice No'),
        ),
    ]
