# Generated by Django 4.0.4 on 2023-03-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0104_delivery_note_sales_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='Invoice_No',
            field=models.CharField(max_length=100, verbose_name='Sales Invoice No'),
        ),
    ]
