# Generated by Django 4.0.4 on 2023-03-31 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0105_alter_delivery_note_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='sales_order_no',
            field=models.CharField(default=datetime.datetime(2023, 3, 31, 12, 23, 53, 50763), max_length=50, verbose_name='Sales Order No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sales',
            name='Invoice_No',
            field=models.CharField(max_length=50, verbose_name='Invoice No'),
        ),
    ]
