# Generated by Django 4.0.4 on 2023-04-03 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0107_delivery_note_delivery_note_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_note',
            name='receipt_note_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 3, 10, 2, 28, 232120), verbose_name='Material Receipt Note Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt_note',
            name='recipt_no',
            field=models.CharField(default=1234, max_length=50, verbose_name='Material Receipt Note No'),
            preserve_default=False,
        ),
    ]
