# Generated by Django 4.0.4 on 2023-04-03 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0108_receipt_note_receipt_note_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note',
            name='gst_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.taxmaster', verbose_name='GST Type'),
        ),
    ]
