# Generated by Django 4.0.4 on 2023-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0109_delivery_note_gst_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocument',
            name='Bill_Date',
            field=models.DateField(verbose_name='Purchase Order Date'),
        ),
        migrations.AlterField(
            model_name='purchasedocument',
            name='SAP_Order_No',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Purchase Order No'),
        ),
    ]
