# Generated by Django 4.0.4 on 2023-04-03 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0110_alter_purchasedocument_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_note',
            name='Customers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='Customer Code'),
        ),
    ]
