# Generated by Django 4.0.4 on 2023-04-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0115_receipt_note_billing_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_note',
            name='receipt_note_date',
            field=models.DateField(verbose_name='MRN Date'),
        ),
        migrations.AlterField(
            model_name='receipt_note',
            name='recipt_no',
            field=models.CharField(max_length=50, verbose_name='MRN No'),
        ),
    ]
