# Generated by Django 4.0.4 on 2023-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0116_alter_receipt_note_receipt_note_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_note',
            name='Total_Amount',
            field=models.CharField(max_length=20, verbose_name='Total Invoice Amount'),
        ),
    ]
