# Generated by Django 4.0.4 on 2023-04-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0117_alter_receipt_note_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_note',
            name='Cash_Discount_Amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Total Discount Amount'),
        ),
    ]
