# Generated by Django 4.0.4 on 2023-04-04 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0118_alter_receipt_note_cash_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='mrn_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 4, 12, 10, 27, 862977), verbose_name='MRN Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='mrn_no',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='account.receipt_note', verbose_name='MRN No'),
            preserve_default=False,
        ),
    ]
