# Generated by Django 4.0.4 on 2023-04-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0120_alter_purchasereturndocument_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailofpurchase',
            name='Purchases_Serial_No',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Puchase Serial No'),
        ),
    ]
