# Generated by Django 4.0.4 on 2023-04-05 12:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0121_alter_detailofpurchase_purchases_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturndocument',
            name='pi_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 12, 22, 41, 458582), verbose_name='PI Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereturndocument',
            name='pi_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.purchaseinvoice', verbose_name='PI No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='Bill_Date',
            field=models.DateField(verbose_name='PR Date'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='SAP_Order_No',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PR No'),
        ),
    ]
