# Generated by Django 4.0.4 on 2023-04-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0122_purchasereturndocument_pi_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='IGST_AMOUNT',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='IGST AMOUNT'),
        ),
    ]
