# Generated by Django 4.0.4 on 2023-04-05 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0124_alter_sales_distributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='cust_po_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 5, 16, 56, 19, 53209), verbose_name='Customer PO Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='cust_po_no',
            field=models.CharField(default='cust0001', max_length=50, verbose_name='Customer PO No'),
            preserve_default=False,
        ),
    ]
