# Generated by Django 4.0.4 on 2023-04-06 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0125_sales_cust_po_date_sales_cust_po_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note',
            name='cust_po_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 10, 31, 54, 838773), verbose_name='Customer PO Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='cust_po_no',
            field=models.CharField(default='cust0001', max_length=50, verbose_name='Customer PO No'),
            preserve_default=False,
        ),
    ]
