# Generated by Django 4.0.4 on 2023-04-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0126_delivery_note_cust_po_date_delivery_note_cust_po_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='Total_Amount',
            field=models.CharField(max_length=20, verbose_name='Total Invoice Amount'),
        ),
    ]
