# Generated by Django 4.0.4 on 2023-04-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0127_alter_delivery_note_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='Bill_Date',
            field=models.DateField(blank=True, null=True, verbose_name='Bill Date'),
        ),
        migrations.AlterField(
            model_name='delivery_note',
            name='Invoice_No',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sales Invoice No'),
        ),
    ]
