# Generated by Django 4.0.4 on 2023-04-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0128_alter_delivery_note_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='Distributors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.distributor', verbose_name='Distributor Code'),
        ),
    ]
