# Generated by Django 4.0.4 on 2023-04-06 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0129_alter_delivery_note_distributors'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='dl_note_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 12, 10, 16, 739294), verbose_name='Delivery Note Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='dl_note_no',
            field=models.ForeignKey(default=18, on_delete=django.db.models.deletion.CASCADE, to='account.delivery_note', verbose_name='Delivery Note No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Distributors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.distributor', verbose_name='Distributor Code'),
        ),
    ]
