# Generated by Django 4.0.4 on 2023-04-06 15:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0130_salesinvoice_dl_note_date_salesinvoice_dl_note_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='Invoice_No',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='sale_return_order',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='sale_return_order_Date',
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sale_invoice_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.salesinvoice', verbose_name='Sales Invoice No'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sales_return_date',
            field=models.DateField(default=datetime.datetime(2023, 4, 6, 15, 23, 16, 94693), verbose_name='Sales Return Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sales_return_no',
            field=models.CharField(default='SR/0001', max_length=50, verbose_name='Sales Return No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='Bill_Date',
            field=models.DateField(verbose_name='Sales Invoice Date'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='CGST_AMOUNT',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='Distributors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.distributor', verbose_name='Distributor Code'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='Total_Invoice_Amount',
            field=models.CharField(max_length=20, null=True, verbose_name='Total Invoice Amount'),
        ),
    ]
