# Generated by Django 4.0.4 on 2023-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0132_alter_salesinvoice_cash_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocument',
            name='SAP_Order_No',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Purchase Order No'),
        ),
    ]
