# Generated by Django 4.0.4 on 2023-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0134_alter_receipt_note_recipt_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='purchase_invoice_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Purchase Invoice No'),
        ),
    ]
