# Generated by Django 4.0.4 on 2023-04-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0135_alter_purchaseinvoice_purchase_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='SAP_Order_No',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='PR No'),
        ),
    ]
