# Generated by Django 4.0.4 on 2023-04-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0136_alter_purchasereturndocument_sap_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='delivery_note_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Delivery Note No'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_order_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sales Order No'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='Invoice_No',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sales Invoice No'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sales_return_no',
            field=models.CharField(max_length=50, unique=True, verbose_name='Sales Return No'),
        ),
    ]
