# Generated by Django 4.0.4 on 2023-04-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0138_alter_detailofpurchase_entity_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_note',
            name='Distributor_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Distributor Name'),
        ),
    ]
