# Generated by Django 4.0.4 on 2023-04-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0139_receipt_note_distributor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_note_detail',
            name='bal_qyn',
            field=models.IntegerField(default=0, verbose_name='BAL QYN'),
        ),
    ]
