# Generated by Django 4.0.4 on 2023-05-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0141_alter_receipt_note_detail_bal_qyn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='CGST_AMOUNT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='CGST AMOUNT'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='IGST_AMOUNT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='IGST AMOUNT'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='SGST_AMOUNT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='SGST AMOUNT'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='Total_GST',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Total GST Amount'),
        ),
    ]
