# Generated by Django 4.0.4 on 2023-05-05 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0143_alter_purchaseinvoice_total_inventory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='CGST_AMOUNT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='CGST AMOUNT'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='IGST_AMOUNT',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=19, verbose_name='IGST AMOUNT'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='SGST_AMOUNT',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='SGST AMOUNT'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='Total_GST',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Total GST'),
        ),
        migrations.AlterField(
            model_name='purchasereturndocument',
            name='Total_Inventory_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Total Inventory Amount'),
        ),
    ]
