# Generated by Django 4.0.4 on 2023-05-05 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0144_alter_purchasereturndocument_cgst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturndocument',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 5, 15, 18, 26, 346486), verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereturndocument',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
    ]
