# Generated by Django 4.0.4 on 2023-05-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0146_alter_warehousestock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='Total_Inventory_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Inventory Amount'),
        ),
    ]
