# Generated by Django 4.0.4 on 2023-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0147_alter_delivery_note_total_inventory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note',
            name='Total_Amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Total Invoice Amount'),
        ),
    ]
