# Generated by Django 4.0.4 on 2023-05-11 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0149_alter_salesreturn_cgst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsofpurchasereturn',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 5, 11, 10, 28, 12, 971676), verbose_name='Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailsofpurchasereturn',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
    ]
