# Generated by Django 4.0.4 on 2023-05-30 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0150_detailsofpurchasereturn_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'get_latest_by': 'purchase_invoice_no'},
        ),
        migrations.AlterField(
            model_name='warehouseitemchild',
            name='Item_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item', unique=True),
        ),
    ]
