# Generated by Django 4.0.4 on 2023-06-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0152_warehouseitemchild_closingbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note_details',
            name='Quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Sales Quantity'),
        ),
        migrations.AlterField(
            model_name='detailofpurchase',
            name='Purchases_Quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Purchase Quantity'),
        ),
        migrations.AlterField(
            model_name='detailsofpurchasereturn',
            name='Purchases_Return_Quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Purchase Return Quantity'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoicelineitem',
            name='Quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='receipt_note_detail',
            name='Quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='saleinvoicelineitem',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales_detail',
            name='Sales_Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales_return_detail',
            name='Sales_Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock_child',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='warehouseitemchild',
            name='Quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
