# Generated by Django 4.0.4 on 2023-06-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0153_alter_delivery_note_details_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note',
            name='warehouse',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.warehouse', verbose_name='Warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt_note',
            name='warehouse',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='account.warehouse', verbose_name='Warehouse'),
            preserve_default=False,
        ),
    ]
