# Generated by Django 4.0.4 on 2023-06-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0156_purchasereturndocument_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt_note_detail',
            name='entity_id',
            field=models.IntegerField(default=1, verbose_name='TID'),
            preserve_default=False,
        ),
    ]
