# Generated by Django 4.0.4 on 2023-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0157_alter_receipt_note_detail_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoicelineitem',
            name='parent_id',
            field=models.CharField(default=1, max_length=30, verbose_name='TID'),
            preserve_default=False,
        ),
    ]
