# Generated by Django 4.0.4 on 2023-06-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0158_alter_purchaseinvoicelineitem_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsofpurchasereturn',
            name='entity_id',
            field=models.IntegerField(default=1, verbose_name='TID'),
            preserve_default=False,
        ),
    ]
