# Generated by Django 4.0.4 on 2023-06-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0159_alter_detailsofpurchasereturn_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_note_details',
            name='entity_id',
            field=models.IntegerField(default=1, verbose_name='TID'),
            preserve_default=False,
        ),
    ]
