# Generated by Django 4.0.4 on 2023-06-20 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0160_alter_delivery_note_details_entity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='base_uom',
        ),
    ]
