# Generated by Django 4.0.4 on 2023-06-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0163_remove_item_purchase_uom_remove_item_sale_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_uom',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_uom',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
