# Generated by Django 4.0.4 on 2023-06-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0164_item_purchase_uom_item_sale_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchase_uom',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sale_uom',
        ),
    ]
