# Generated by Django 4.0.4 on 2023-06-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0166_item_purchase_uom_item_sale_uom'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailofpurchase',
            name='p_uom',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='account.uom', verbose_name='UOM'),
            preserve_default=False,
        ),
    ]
