# Generated by Django 4.0.4 on 2023-06-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0167_detailofpurchase_p_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailofpurchase',
            name='p_uom',
        ),
    ]
