# Generated by Django 4.0.4 on 2023-06-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0168_remove_detailofpurchase_p_uom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitemchild',
            name='closingbalance',
        ),
    ]
