# Generated by Django 4.0.4 on 2023-06-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0169_remove_warehouseitemchild_closingbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='isactive',
            field=models.BooleanField(default=0, verbose_name='Is Active'),
        ),
    ]
