# Generated by Django 4.0.4 on 2023-06-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0170_zone_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmaster',
            name='isactive',
            field=models.BooleanField(default=0, verbose_name='Is Active'),
        ),
    ]
