# Generated by Django 4.0.4 on 2023-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0172_statemaster_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymaster',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
    ]
