# Generated by Django 4.0.4 on 2023-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0173_citymaster_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy1',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='hierarchy2',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='hierarchy3',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='hierarchy4',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='hierarchy5',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
    ]
