# Generated by Django 4.0.4 on 2023-06-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0174_hierarchy1_isactive_hierarchy2_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='item',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
    ]
