# Generated by Django 4.0.4 on 2023-06-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0175_customer_isactive_distributor_isactive_item_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbpricemaster',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='taxmaster',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='unit',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='uom',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
    ]
