# Generated by Django 4.0.4 on 2023-06-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0176_dbpricemaster_isactive_rolemaster_isactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='sales_detail',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
    ]
