# Generated by Django 4.0.4 on 2023-07-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0177_sales_isactive_sales_detail_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='current_status',
        ),
        migrations.AddField(
            model_name='delivery_note',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='delivery_note_details',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='ordergenerator',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='purchasereturndocument',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='receipt_note',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='isactive',
            field=models.BooleanField(default=1, verbose_name='Is Active'),
        ),
    ]
