# Generated by Django 4.0.4 on 2023-07-14 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0182_alter_warehouseitemchild_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitemchild',
            name='Item_Code',
        ),
    ]
