# Generated by Django 4.0.4 on 2023-07-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0184_warehouseitemchild_itms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouseitemchild',
            name='itms',
        ),
    ]
