# Generated by Django 4.0.4 on 2023-07-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0187_warehousestock_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitemchild',
            name='Discount',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Sales Discount(%)'),
        ),
    ]
