# Generated by Django 4.0.4 on 2023-07-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0188_alter_warehouseitemchild_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailofpurchase',
            name='Total_Amounts',
        ),
    ]
