# Generated by Django 4.0.4 on 2023-07-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0189_remove_detailofpurchase_total_amounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailofpurchase',
            name='purchase',
        ),
    ]
