# Generated by Django 4.0.4 on 2023-07-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0190_remove_detailofpurchase_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_note_detail',
            name='receiptnotes',
        ),
        migrations.AlterField(
            model_name='receipt_note_detail',
            name='bal_qyn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BAL QYN'),
        ),
    ]
