# Generated by Django 4.0.4 on 2023-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0193_purchaseinvoicelineitem_bal_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt_note_detail',
            name='bal_qyn',
        ),
        migrations.AddField(
            model_name='receipt_note_detail',
            name='bal_qty',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='BAL QTY'),
        ),
    ]
