# Generated by Django 4.0.4 on 2023-07-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0194_remove_receipt_note_detail_bal_qyn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoicelineitem',
            name='Serial_No',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial No'),
        ),
    ]
