# Generated by Django 4.0.4 on 2023-07-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0197_alter_purchaseinvoicelineitem_bal_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsofpurchasereturn',
            name='Details_Of_Purchase_Return',
        ),
        migrations.RemoveField(
            model_name='detailsofpurchasereturn',
            name='Total_Amounts',
        ),
        migrations.RemoveField(
            model_name='purchasereturndocument',
            name='PO_No',
        ),
    ]
