# Generated by Django 4.0.4 on 2023-07-19 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0199_remove_sales_detail_reference_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='Distributor_Name',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='Distributors',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='R_O_Amount',
        ),
    ]
