# Generated by Django 4.0.4 on 2023-07-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0200_remove_sales_distributor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_note',
            name='Distributors',
        ),
        migrations.RemoveField(
            model_name='delivery_note',
            name='R_O_Amount',
        ),
        migrations.RemoveField(
            model_name='delivery_note_details',
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='delivery_note_details',
            name='Deliverynotes',
        ),
        migrations.RemoveField(
            model_name='delivery_note_details',
            name='Reference_No',
        ),
    ]
