# Generated by Django 4.0.4 on 2023-07-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0201_remove_delivery_note_distributors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note_details',
            name='bal_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='BAL QTY'),
        ),
    ]
