# Generated by Django 4.0.4 on 2023-07-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0203_alter_delivery_note_details_serial_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleinvoicelineitem',
            options={'verbose_name': 'Sales Invoice LineItem'},
        ),
        migrations.RemoveField(
            model_name='saleinvoicelineitem',
            name='Batch',
        ),
        migrations.RemoveField(
            model_name='saleinvoicelineitem',
            name='Reference_No',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='Distributor_Name',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='Distributors',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='R_O_Amount',
        ),
        migrations.AddField(
            model_name='saleinvoicelineitem',
            name='bal_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='BAL QTY'),
        ),
    ]
