# Generated by Django 4.0.4 on 2023-07-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0204_alter_saleinvoicelineitem_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales_return_detail',
            name='Reference_No',
        ),
        migrations.RemoveField(
            model_name='sales_return_detail',
            name='SalesDetails',
        ),
        migrations.RemoveField(
            model_name='sales_return_detail',
            name='Sales_Batch',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='Details_Of_Sales_Return',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='Distributor_Name',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='Distributors',
        ),
        migrations.RemoveField(
            model_name='salesreturn',
            name='RO_Amount',
        ),
    ]
