# Generated by Django 4.0.4 on 2023-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0206_rename_order_no_warehousestock_w_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailofpurchase',
            name='Purchases_Quantity',
            field=models.IntegerField(default=0, verbose_name='Purchase Quantity'),
        ),
    ]
