# Generated by Django 4.0.4 on 2023-07-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0208_alter_sales_detail_sales_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousestock',
            name='w_order_no',
        ),
    ]
