# Generated by Django 4.0.4 on 2023-07-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0209_remove_warehousestock_w_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousestock',
            name='w_order_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stock ID'),
        ),
    ]
