# Generated by Django 4.0.4 on 2023-07-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0211_detailofpurchase_bal_qty_sales_detail_bal_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailofpurchase',
            name='bal_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='BAL QTY'),
        ),
    ]
