# Generated by Django 4.0.4 on 2023-08-02 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0217_delete_stocksummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mrn_Qty', models.IntegerField(default=0, verbose_name='Purchase Qty')),
                ('purchase_return_qty', models.IntegerField(default=0, verbose_name='Purchase Return Qty')),
                ('delivery_note_qty', models.IntegerField(default=0, verbose_name='Sale Qty')),
                ('sale_return_qty', models.IntegerField(default=0, verbose_name='Sale Return Qty')),
                ('closing_balance', models.CharField(blank=True, max_length=100, null=True, verbose_name='Closing Balance')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item', verbose_name='Item')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.warehouse', verbose_name='Warehouse')),
            ],
        ),
    ]
