# Generated by Django 4.0.4 on 2023-08-02 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0219_stocksummary_uom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksummary',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.item', unique=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.warehouse', unique=True, verbose_name='Warehouse'),
        ),
    ]
