# Generated by Django 4.0.4 on 2023-08-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0222_stocksummary_item_stocksummary_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksummary',
            name='Mrn_Qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Purchase Qty'),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='delivery_note_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sale Qty'),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='purchase_return_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Purchase Return Qty'),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='sale_return_qty',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sale Return Qty'),
        ),
    ]
