# Generated by Django 4.0.4 on 2023-08-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0223_alter_stocksummary_mrn_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksummary',
            name='item',
            field=models.IntegerField(default=0, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='warehouse',
            field=models.IntegerField(default=0, verbose_name='Warehouse'),
        ),
    ]
