# Generated by Django 4.0.4 on 2023-08-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0224_alter_stocksummary_item_alter_stocksummary_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksummary',
            name='item',
            field=models.IntegerField(default=0, unique=True, verbose_name='Item'),
        ),
    ]
