# Generated by Django 4.0.4 on 2023-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0225_alter_stocksummary_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocksummary',
            name='item',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='warehouse',
            field=models.CharField(default=0, max_length=100, verbose_name='Warehouse'),
        ),
    ]
