# Generated by Django 4.0.4 on 2023-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0226_alter_stocksummary_item_alter_stocksummary_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksummary',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
