# Generated by Django 4.0.4 on 2023-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0227_stocksummary_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocksummary',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='stocksummary',
            name='update_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='item',
            field=models.IntegerField(default=0, unique=True, verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='stocksummary',
            name='warehouse',
            field=models.IntegerField(default=0, verbose_name='Warehouse'),
        ),
    ]
