# Generated by Django 4.0.4 on 2023-08-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0228_remove_stocksummary_updated_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocksummary',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
