# Generated by Django 4.0.4 on 2023-08-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0229_rename_update_on_stocksummary_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksummary',
            name='itm_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Item Code'),
        ),
        migrations.AddField(
            model_name='stocksummary',
            name='w_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Warehouse Code'),
        ),
    ]
