# Generated by Django 4.0.4 on 2023-08-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0231_alter_stocksummary_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocksummary',
            name='OP',
            field=models.IntegerField(default=0, verbose_name='Opening Balance'),
        ),
    ]
