# Generated by Django 4.0.4 on 2023-08-16 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0233_rename_order_no_receipt_note_p_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitemchild',
            name='w_house',
            field=models.IntegerField(null=True, verbose_name='Warehouse'),
        ),
    ]
