# Generated by Django 4.0.4 on 2023-08-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0234_warehouseitemchild_w_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_note_detail',
            name='MRN_QTY',
            field=models.IntegerField(default=0),
        ),
    ]
