# Generated by Django 4.0.4 on 2023-08-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0236_purchaseinvoicelineitem_pi_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note_details',
            name='DN_QTY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saleinvoicelineitem',
            name='SI_QTY',
            field=models.IntegerField(default=0),
        ),
    ]
