# Generated by Django 4.0.4 on 2023-08-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0237_delivery_note_details_dn_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='status',
        ),
    ]
