# Generated by Django 4.0.4 on 2023-08-24 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0238_remove_zone_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_detail',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.sales'),
        ),
    ]
