# Generated by Django 4.0.4 on 2023-08-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0239_sales_detail_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_note_details',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.delivery_note'),
        ),
        migrations.AddField(
            model_name='saleinvoicelineitem',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.salesinvoice'),
        ),
        migrations.AddField(
            model_name='sales_return_detail',
            name='salereturn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.salesreturn'),
        ),
    ]
