# Generated by Django 4.0.4 on 2023-08-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0240_delivery_note_details_note_saleinvoicelineitem_inv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailofpurchase',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.purchasedocument'),
        ),
    ]
