# Generated by Django 4.0.4 on 2023-08-24 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0241_detailofpurchase_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_note_detail',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.receipt_note'),
        ),
    ]
