# Generated by Django 4.0.4 on 2023-08-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0243_detailsofpurchasereturn_preturn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasedocument',
            name='SAP_Order_Date',
        ),
        migrations.RemoveField(
            model_name='purchasedocument',
            name='Supplier_Invoice_No',
        ),
    ]
