# Generated by Django 4.0.4 on 2023-08-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0245_remove_receipt_note_detail_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousestock',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
