# Generated by Django 4.0.4 on 2022-05-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_Date', models.DateField()),
                ('Invoice_No', models.CharField(max_length=50)),
                ('Tally_MasterID', models.CharField(blank=True, max_length=15, null=True)),
                ('Total_GST', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('IGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Cash_Discount_Amount', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True)),
                ('R_O_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Total_Invoice_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
