# Generated by Django 4.0.4 on 2022-05-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('johndocument', '0003_sales_total_inventory_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
